### ISSUE TITLE
Blank not reserved

### ISSUE THREAD

**Issue by laterdayi** [itisnajim/yaml_magic#5]
```
flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png

# flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/launcher_icon.png
```

saved 

```
flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
# flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/launcher_icon.png
```

mages/launcher_icon.png
```
